#!/bin/bash

function compose_destroy() {
  docker-compose -p=demo-vault-docker down -v --rmi local
  find vault/data -mindepth 1 ! -name '*.md' -delete
  find vault/logs -mindepth 1 ! -name '*.md' -delete
  exit 0
}
trap cleanup SIGKILL SIGINT

function compose_build() {
  docker-compose -p=demo-vault-docker up -d
  exit 0
}

function compose_rebuild() {
  docker-compose -p=demo-vault-docker down -v --rmi local 
  find vault/data -mindepth 1 ! -name '*.md' -delete
  find vault/logs -mindepth 1 ! -name '*.md' -delete
  docker-compose -p=demo-vault-docker up -d
}

for arg in "$@"
do
    case $arg in
        build)
        compose_build
        shift
        ;;
        destroy)
        compose_destroy
        shift
        ;;
        rebuild)
        compose_rebuild
        shift
        ;;
        *)
        echo "Command not found: try 'build', 'destroy', or 'rebuild'"
        shift
        ;;
    esac
done
