#!/bin/bash

project_prefix=vault-demo

case "$1" in
    single)
      pushd standalone/
      docker-compose -p="$project_prefix-$1-instance" up -d
      popd
      ;;
    cluster)
      pushd cluster/
      docker-compose -p="$project_prefix-$1" up -d
      popd
      ;;
    *)
      printf "\n%s" \
      "Creates the Vault deployment based on size desired." \
      "Usage: $script_name build [single|cluster]" \
      "" \
      ""
      ;;
esac