#!/bin/bash

project_prefix=vault-demo

case "$1" in
    single)
      pushd standalone/
      docker-compose -p="$project_prefix-$1-instance" down -v --rmi local
      find vault/tmp -mindepth 1 ! -name '*.md' -delete
      find vault/tmp -mindepth 1 ! -name '*.md' -delete
      popd
      ;;
    cluster)
      pushd cluster/
      docker-compose -p="$project_prefix-$1" down -v --rmi local
      find vault/tmp -mindepth 1 ! -name '*.md' -delete
      find vault/tmp -mindepth 1 ! -name '*.md' -delete
      popd
      ;;
    *)
      printf "\n%s" \
      "Destroys the Vault demo components." \
      "Usage: $script_name destroy [single|cluster]" \
      "" \
      ""
      ;;
  esac