#!/bin/bash

project_prefix=vault-demo

case "$1" in
    single)
      compose_destroy "$@"
      compose_build "$@"
      ;;
    cluster)
      compose_destroy "$@"
      compose_build "$@"
      ;;
    *)
      printf "\n%s" \
      "Destroys & rebuilds the Vault demo environment." \
      "Usage: $script_name rebuild [single|cluster]" \
      "" \
      ""
      ;;
  esac