version: '3.8'

networks:
  internal:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: ${NWCIDRBLOCK}

services:
  vault-server:
    image: hashicorp/vault-enterprise:1.10.4-ent
    hostname: vault-server
    container_name: vault-server
    depends_on:
      - splunk
    networks:
      - internal
    ports:
      - "18200:8200"
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      ROOT_NAMESPACE: ${ROOT_NAMESPACE}
    volumes:
      - ../assets/vault/policies:/vault/policies:ro
      - ../assets/vault/config:/vault/config:ro
      - ../assets/vault/plugins:/vault/plugins:ro
      - ./vault/tmp:/vault/logs
      - ./vault/tmp:/tmp/outputs
    tmpfs:
      - /vault/file
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/standalone.hcl

  helper:
    hostname: helper
    container_name: helper
    depends_on:
      - vault-server
    #build: ../assets/helper/.
    image: vaultdemo-helper:latest
    stdin_open: true # docker run -i
    tty: true
    environment:
      - PGPASSWORD=${POSTGRES_PASSWORD}
    env_file: .env
    volumes:
      - ../assets/vault:/vault
      - ../assets/postgres:/tmp/seed-db:ro
      - ./vault/tmp:/tmp/outputs
    networks:
      - internal

  helper-mfa:
    hostname: helper-mfa
    container_name: helper-mfa
    depends_on:
      - vault-server
    #build: ../assets/helper/.
    image: vaultdemo-helper-mfa:latest
    stdin_open: true # docker run -i
    tty: true
    environment:
      - PGPASSWORD=${POSTGRES_PASSWORD}
    env_file: .env
    volumes:
      - ../assets/vault:/vault:ro
      - ./vault/tmp:/tmp/outputs
    networks:
      - internal

  helper-approle:
    hostname: helper-approle
    container_name: helper-approle
    depends_on:
      - vault-server
    #build: ../assets/helper/.
    image: vaultdemo-helper-approle:latest
    stdin_open: true # docker run -i
    tty: true
    environment:
      - PGPASSWORD=${POSTGRES_PASSWORD}
    env_file: .env
    volumes:
      - ../assets/vault:/vault:ro
      - ../assets/helper-approle/scripts:/tmp/scripts
      - ./vault/tmp:/tmp/outputs:ro
    networks:
      - internal

  splunk:
    networks:
      - internal
    image: splunk/splunk:8.1
    hostname: splunk
    container_name: splunk
    volumes:
      - ../assets/splunk/vault-app-for-splunk:/opt/splunk/etc/apps/vault
      - ./vault/tmp:/vault/logs:ro
    environment:
      - SPLUNK_USER:root
      - SPLUNK_START_ARGS='--accept-license --answer-yes'
      - SPLUNK_PASSWORD=${password}
    ports:
      - 18000:8000

  telegraf:
    networks:
      - internal
    image: telegraf:alpine
    hostname: telegraf
    container_name: telegraf
    volumes:
      - ../assets/telegraf/file_output.conf:/etc/telegraf/telegraf.conf:ro
      - ./vault/tmp:/tmp/outputs
    ports:
      - 18125:8125/udp

  postgres:
    image: postgres:11-alpine
    hostname: postgres
    container_name: postgres
    networks:
      - internal
    env_file: .env #configure postgres
    ports:
      - '15432:5432'
    volumes: 
      - ../assets/postgres:/tmp/seed-db:ro

  ubuntu:
    hostname: ubuntu
    container_name: ubuntu
    #build: ../assets/ubuntu-ssh/.
    image: vaultdemo-ubuntu-ssh:latest
    stdin_open: true 
    tty: true
    env_file: .env
    networks:
      - internal

  centos:
    hostname: centos
    container_name: centos
    #build: ../assets/ubuntu-ssh/.
    image: centos:centos7.9.2009
    stdin_open: true 
    tty: true
    env_file: .env
    networks:
      - internal